---
title: "Introduction to R Programming"
subtitle: "FISH 552 &nbsp; &nbsp; University of Washington &nbsp; &nbsp; Autumn 2020"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

<br>

# Summer 2020 Updates

* Check out the [Enrollment FAQ](faq.html)
* FISH 552 is the 1st in a series of 2 courses. 
  * FISH 552 runs for 5 weeks: Wednesday 09/30/2020 to Wednesday 10/28/2020
  * FISH 553 runs for the remaining 5 weeks: Monday 10/31/2020 to Wednesday 12/09/2020
* How to enroll: The Autumn 2020 SLN for FISH 552 is 15320
* How to enroll: The Autumn 2020 SLN for FISH 553 is 15321
* You have to enroll in FISH 552 and 553 separately, if you want to take both.
* You can enroll in just FISH 552 or 553 if this suits your educational goals
* **I am preparing this 2020 course as a synchronous online offering--this means that we will meet during our scheduled course time via Zoom**

<br>

# Course overview

This course will introduce students to the R programming language and RStudio integrated development environment within the context of the aquatic and fishery sciences. Students will learn how to read data files into RStudio, create exploratory plots, manipulate data to prepare for analysis, and write functions. This course also introduces students to best practices for programming in R (*e.g.*, commenting, syntax spacing, code testing, and using R projects). In general, students will use case studies from various fisheries disciplines and focus on critically evaluating data documentation and quality assurance, integrating multiple data sources, and preparing data for statistical analyses.

<!-- <br> -->

<!-- # Learning objectives -->
<!-- * one -->
<!-- * two -->
<!-- * three -->
<!-- * four -->
<!-- * five -->

<br>

# Instructor

Kristin Privitera-Johnson

PhD Student, School of Aquatic & Fishery Sciences

Office Hours: TBA, FSH 336

Email: [kpjohns@uw.edu](mailto:kpjohns@uw.edu)

<br>

# Meeting times & locations
M/W from 11:30 am - 1:20 pm in ~~MGH 030~~ via Zoom

First class meeting: 09/30/2020 

Last class meeting: 10/28/2020

Followed immediately by 10 lectures of FISH 553 Advanced R Programming from 10/31/2020 to 12/09/2020 (requires separate enrollment).

<br>

# Pre-requisites
There are no course pre-requisites. 

<br>

# Required readings
No required textbooks. All readings are provided by the instructor.

<br>

# Inclusivity
I teach this course with the intent to serve students from all backgrounds and perspectives, to address students’ learning needs both in and out of class, and to honor the diversity that students bring to this class as a resource, strength, and benefit. I intend to design and present course materials and activities that are respectful of diversity: gender, sexual orientation, disability, age, socioeconomic status, ethnicity, race, culture, perspective, and other background characteristics. I acknowledge that it is possible that there may be both overt and covert biases in the material due to the lens with which it was written, even though the material is primarily of a scientific nature. Your suggestions about how to improve the value of diversity in this course are encouraged and appreciated. Please let me know (in person or electronically) ways to improve the effectiveness of the course for you personally or for other students or student groups. I will provide opportunities for anonymous feedback throughout the course.

I strive to create a learning environment for my students that supports a diversity of thoughts, perspectives and experiences, and honors your identities. To help accomplish this:

*	If you have a name/or set of pronouns that differ from those that appear in your official UW records, please let me know at your convenience.

* If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. I want to be a resource for you. If you prefer to speak with someone outside of the course, the College of the Environment Diversity, Equity, and Inclusion office, is an excellent resource.

* I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it. (Again, anonymous feedback is always an option).

<br>

# Classroom conduct
I am dedicated to providing a welcoming and supportive environment for all people, regardless of background, identity, physical appearance, or manner of communication. Any form of language or behavior used to exclude, intimidate, or cause discomfort will not be tolerated. This applies to all course participants (instructor, students, guests). In order to foster a positive and professional learning environment, I encourage the following kinds of behaviors:

* Use welcoming and inclusive language

* Be respectful of different viewpoints and experiences

* Gracefully accept constructive criticism

* Show courtesy and respect towards others

**Please note**: If you believe you have been a victim of an alleged violation of the [Student Conduct Code](https://www.washington.edu/admin/rules/policies/WAC/478-121TOC.html) or you are aware of an alleged violation of the [Student Conduct Code](https://www.washington.edu/admin/rules/policies/WAC/478-121TOC.html), you have the right to [report it to the University](https://www.washington.edu/cssc/for-students-2/).

<br>

# Evaluation & grading
To be added. I am currently reviewing the course content and adapting activities for the Autumn 2020 online offering.

<br>

# Access & accommodations

All students deserve access to the full range of learning experiences, and the University of Washington is committed to creating inclusive and accessible learning environments consistent with federal and state laws. 

### Disabilities

If you have already established accommodations with Disability Resources for Students (DRS), please communicate your approved accommodations to me at your earliest convenience so we can discuss your needs in this course. If you have not yet established services through DRS, but have a temporary health condition or permanent disability that requires accommodations (*e.g.*, mental health, learning, vision, hearing, physical impacts), you are welcome to contact DRS at 206-543-8924 or via [email](mailto:uwdrs@uw.edu) or their [website](https://depts.washington.edu/uwdrs/). DRS offers resources and coordinates reasonable accommodations for students with disabilities and/or temporary health conditions.  Reasonable accommodations are established through an interactive process between you, your instructor(s) and DRS.

### Religious observances

Students who expect to miss class or assignments as a consequence of their religious observance will be provided with a reasonable accommodation to fulfill their academic responsibilities. Absence from class for religious reasons does not relieve students from responsibility for the course work required during the period of absence. It is the responsibility of the student to provide the instructor with advance notice of the dates of religious holidays on which they will be absent. Students who are absent will be offered an opportunity to make up the work, without penalty, within a reasonable time, as long as the student has made prior arrangements.

<br>

# Technology
To be added. I am currently reviewing the course content and adapting activities for the Autumn 2020 online offering.

<br>

# Academic integrity
Faculty and students at the University of Washington are expected to maintain the highest standards of academic conduct, professional honesty, and personal integrity. Plagiarism, cheating, and other academic misconduct are serious violations of the [Student Conduct Code](https://www.washington.edu/cssc/for-students/academic-misconduct/). I have no reason to believe that anyone will violate the Student Conduct Code, but *I will have no choice* but to refer any suspected violation(s) to the College of the Environment for a Student Conduct Process hearing. Students who have been guilty of a violation will receive zero points for the assignment in question.

<br>

# Mental health

We are in the midst of an historic pandemic that is creating a variety of challenges for everyone. If you should feel like you need some help, please consider the following resources available to students.

**If you are experiencing a life-threatening emergency, please dial 911**.  

[**Crisis Clinic**](http://www.crisisclinic.org/)  
Phone: 206-461-3222 or toll-free at 1-866-427-4747   

[**UW Counseling Center**](https://www.washington.edu/counseling/services)  
Phone: 206-543-1240  
[Immediate assistance](https://www.washington.edu/counseling/services/crisis/)

[**Let’s Talk**](https://wellbeing.uw.edu/virtual-lets-talk/)

[**Hall Health Mental Health**](https://wellbeing.uw.edu/unit/hall-health)

<br>

# Safety

If you feel unsafe or at-risk in any way while taking any course, contact [SafeCampus](https://www.washington.edu/safecampus/) (206-685-7233) anytime&ndash;no matter where you work or study&ndash;to anonymously discuss safety and well-being concerns for yourself or others. SafeCampus can provide individualized support, discuss short- and long-term solutions, and connect you with additional resources when requested. For a broader range of resources and assistance see the [Husky Health & Well-Being website](https://wellbeing.uw.edu/).

<br>

# Food pantry

No student should ever have to choose between buying food or textbooks. The UW Food Pantry helps mitigate the social and academic effects of campus food insecurity. They aim to lessen the financial burden of purchasing food by providing students access to shelf-stable groceries, seasonal fresh produce, and hygiene products at **no cost**. Students can expect to receive 4 to 5 days' worth of supplemental food support when they visit the Pantry, located on the north side of Poplar Hall at the corner of NE 41<sup>st</sup> St and Brooklyn Ave NE. Visit the [Any Hungry Husky website](https://uw.edu/anyhungryhusky) for additional information, including operating hours and additional food support resources.

<br>

<center>*This site was last updated at `r format(Sys.time(), "%H:%M")` on `r format(Sys.Date(), "%d %b %Y")`*</center>
